version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongo:27017/etaration

  mongo:
    image: mongo:5.0
    container_name: movie-mongo-etaration
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
